### ISSUE TITLE
SEAD Training Range

### ISSUE THREAD

**Issue by jkhoel** [132nd-vWing/ATRM#1]
30 x 30 NM (Killbox-sized) Range with multiple types of SAM systems inside, activated from F10 Menus.

Idea is to have a place to train basic offensive tactics against known threats. Also, if this range could be inside a larger range, then we could use it for strikes

132nd.Dex

**Comment by jkhoel** [comment]
If the larger range could also have some type of IADS, that would be perfect. I can help design it :)

**Comment by 132ndNeck** [comment]
I will create various SEAD ranges. 
Both for normal TRP training, and for more advanced LFE (Large Force Exercise or ) trainings (scenariotraining)

I will use functionality current implemented in the TRM and OPUF for the IADS.

@jkhoel Very interested in your suggestion for IADS aswell, so share them here, and I will compile and prepare a request for Entropy once I have the details of the ranges in place.

**Comment by jkhoel** [comment]
With reference to the work-in-progress [SEAD TTP](https://drive.google.com/file/d/1lAGrnH428L7LDVyRsV9OV9katMfIFewo/view?usp=sharing), 'Execution' chapter; The range(s) should accommodate training of all the offensive tactics currently detailed there.

Long-range SAM suppression is more along the lines of a strike, so would require a larger area - possibly dotted with MERAD/SHORAD systems - making it an IADS.
Medium-/Short-range would be good to train against in a "box" (or the systems weapon engagement zone - WEZ). As these are beginner level (SA2/SA3/SA8/SA6 aka less modern) to more advanced (SA11/SA15/SA13 aka more modern). 

For IADS it would be cool if we could have different variations that we could change over time, and each variation selectable via the F10 menu. Say we put out different systems - lets just call them system 1 trough 10:
- Variation 1:  Systems 2, 4, 6 and 10 comes online
- Variation 2: Systems 1, 3, 5, 6, 9 etc.. 

I think this would make it so that over time, we could change those setups more easily via just selecting what comes online via the script - rather than having to place new targets around. Each variation should be based on either a training setup, or on knowledge about how IADS are organized (tactics, coverage and era perhaps)

It would also be nice if IADS logic was selectable:
1. Easy (Normal DCS Behavior - Systems don't go offline and all that jazz)
2. Medium (IADS will shut down if a HARM is fired)
3. Advanced (If the system has multiple radars, it will shut down the one fired on, and perhaps turn on another - keeping its coverage)

I think if we could do some of this, then we would have a very dynamic setup for training everything from basic SEAD to advanced tactics

**Comment by 132ndNeck** [comment]
Sounds good, I will make sure to setup some ranges with the necessary IADS functionality.
I will coordinate with Entropy on how we can do this in the best possible way.

But should be doable as both a IADS system for scenariotrainig, and for specific ranges for TRP basic training.

**Comment by 132ndNeck** [comment]
Range 2 is availeble now for basic SEAD practice.

Range 10 is availeble for work against a IADS.

**Comment by 132ndNeck** [comment]
Range 12 is availeble with a IADS

**Comment by 132nd-Entropy** [comment]
could this be closed?

**Comment by 132ndNeck** [comment]
Yes.
Closing it now.
