### ISSUE TITLE
On demand AI defence (of course, here it is)

### ISSUE THREAD

**Issue by thebgpikester** [132nd-vWing/ATRM#10]
Segmented A-A area via dispatcher with cold war borders, placed in an area like Shiraz or Kerman, with a box of reasonable size away from a2g ranges.

Countering usual objections:
a) The cold war borders prevent AI traveling to areas you don't want them in. We've seen OPUF, we don't really see them coming south so we know it's contained
b) There's a lot of land mass, so deep strikes are still available almost to the limit of Hornet/Viper fuel ranges in the "other" corner. 150nm travel is available
c) Missile trainer is still available
d) It's very easy to script stopping it and deleting all aircraft mid mission. Can be via F10 menu where other ranges are, or even via codewords placed in markers
e) Not suggesting it is always present - AI will not be there by default
f) It doesn't imply replacing Humans where possible
g) Should be balanced with appropriate Redfor slots in Shiraz/Kerman

Design: 

- Mostly limited by menu space if menu's are what are being used
- You can have GCI only, CAP only, or both
- You can setup specific AI plane types via the menu, or random, or fixed
- Requires a single AWACS or EWR that has coverage over the box.
- You can change the box's size dynamically too

Why:

Raising the correct amount of people for anything large scale is very difficult. You can't get multiple flights of F-14 players (8 players) easily to practice large scale air to air and training often resolves down to 1v1, and maximum (and rare) 2v2.

It takes a lot of effort to raise A-A events with anything but Tomcat vs Hornet, so we train and get bogged down in the same aircraft/weapon which affects testing minimum ranges, not learning ranges (who here has actually fought an R40 engagement or knows what it is?)

Having both sides with humans involves originating from the same airbase or long travel times to the MOA, whereby you are lucky to get 2-3 sets in due to fuel, which means 90 minutes of ferry and startup for 10 minutes of combat - which is an inferior learning pace.

There's nothing complex in this, the question of why _not_ usually cites:
- Safety and disruption possibilities to other trainers
- Lack of human behaviour - we _can_  use Humans, but the problem is numbers and dealing with Human lateness, availability and module restrictions
- Server Performance (I've never heard/seen a single instance of the server becoming sub optimal with AI, and we can turn it on/off and customise it)

**Comment by 132ndNeck** [comment]
I totally agree that it is needed 

I suggest a seperate training mission for this, with unlimited fuel, unlimited weapons, air start in order to get a maximum effectice A-A training against AI.

Then any IP that want to host A-A training can do that in a easier and more time-effective way, as the focus is not on the full scale training immersion that we normally want for a standard training, but more a effective way of setting it up to do A-A training.

**Comment by thebgpikester** [comment]
OK, will move a discussion back to discord or forums then.

**Comment by 132nd-Entropy** [comment]
this was not followed up on, closing
