### ISSUE TITLE
T4.2 vehicles did not assume their set formations

### ISSUE THREAD

**Issue by steven-omaha** [132nd-vWing/ATRM#100]
All the convoys at T4.2 moved in column formation, even though they were set to different formations in the ME. One convoy assumed their correct formation after some units were destroyed. 

Maybe it helps if waypoint 0 for all convoys is set to the formation instead of off-road. Their formations currently begin at waypoint 1.

**Comment by 132ndNeck** [comment]
Adjusted all convoys and added formation at waypoint 0.
