### ISSUE TITLE
CVN-73 w battle group and Flights

### ISSUE THREAD

**Issue by 132ndJaeger** [132nd-vWing/ATRM#103]
Want to change/add CVN-73 and it's battle group with appropriate speed.
Also add 4-5x2 Ship F/A-18C groups and 1-2x4 Ship F/!-18C group(s).
And 3-4x2 Ship F-14B groups and 1-2x4Ship F-14B group(s)

**Comment by 132ndNeck** [comment]
CVN-73 is added.

Just a question: Do the 4 escort ships serve any purpose? Or can they be deleted (reducing strain on the server as much as possible, by taking out things that are just eye candy and focusing on items that is actually used)
