### ISSUE TITLE
Add Mi8 spawning spot to cvns?

### ISSUE THREAD

**Issue by Looney1976** [132nd-vWing/ATRM#104]
Is it possible to add 2 spawn spots on the cvns for Mi8 operations directly from the carrier?

Another way would be to add the Tarawa and spawn on there but as far as I know this may still be bugged. I'll try it myself to make sure.

**Comment by 132ndNeck** [comment]
The carrier is 40-50 nm out to sea. Will there be events (except the 108th deployment flight where MI-8 support was requested) where a pilot will start at the carrier and fly out there?

If yes, then it is probably doable (I have not checked on the carrier and RW operations).
If no, then it is likely better to just put in a MI-8 for that specific event, and not place on permanently on the carrier.

**Comment by 132nd-Entropy** [comment]
it would be easily doable and it would also not strain the server, since nothing spawns out there unless people use it. Im happy to put it in, if its used? (but since you requested it, I guess you gonna use it? @Looney1967 ?)

**Comment by Looney1976** [comment]
The spawning on Tarawa is fixed now. With the aim to be able to support maritime operations I'd like to have 2 Mi8 spawn points on either the CVN or Tarawa.

**Comment by 132nd-Entropy** [comment]
rgr
