### ISSUE TITLE
CVN-73 No TACAN

### ISSUE THREAD

**Issue by 132ndEvo** [132nd-vWing/ATRM#107]
No TACAN from CVN-73. All aircraft reported the same

**Comment by 132nd-Entropy** [comment]
tacan, freqs etc were set by airboss in the past. when we took out the airboss script, apparently setting freqs etc manually on the red carrier was overlooked, will fix

**Comment by 132nd-Entropy** [comment]
or are we talking about the blue carrier, this is strange, I didnt touch this one, not sure what the issue is here

**Comment by 132ndEvo** [comment]
It was the blue carrier

**Comment by 132ndJaeger** [comment]
It was both

**Comment by 132nd-Entropy** [comment]
yesterday's event host modified the mission file and probably by accident deleted teh tacan and icls settings. works fine on the blue carrier on the ATRM

**Comment by 132nd-etcher** [comment]
Don't mind me, just missing the AirBoss 👼
