### ISSUE TITLE
Carrier wind direction and speed

### ISSUE THREAD

**Issue by 132ndEvo** [132nd-vWing/ATRM#108]
Blue carrier CVN-71 had an 11 kt tailwind over the deck.
Blue carrier CVN-73 had no wind over the deck.

**Comment by 132nd-Entropy** [comment]
there is two solutions to this that I can see, either the AIRBOSS script gets implemented again, despite the fact that some people were against it, or hosts need to manually correct the course of the carrier groups whenever they change the windspeeds. AFAIK there is no way to influence the speed of the boat via the F10 map like you can move ground units, but I might be wrong

**Comment by 132ndEvo** [comment]
so doing some experiments you can control the carrier but the option of game master only has to be selected and you need to be in the game master slot. So maybe whoever spawns in first turns the carrier and sets the speed?

**Comment by 132nd-Entropy** [comment]
sounds like a good workaround!

**Comment by 132nd-Inigo** [comment]
There are very good benefits for the AIRBOSS script from hoster perspective. The carrier could always follow the coast, making it close to the action, and turn when needed, in addition to all other benefits that come with it.
Now if the mission host wishes to make mission abit different from the default constant crosswind and sets wind from the West (or the East), he needs to set the carrier to go away from the cost (or other way around). After couple hours of mission time the distance can get very large (even more if mission starts an hour before mission time). After those couple hours the carrier might start coming back, making it go with the wind. Theres just that much space and time the carrier can move in optimal direction.

Controlling the carrier might brake the TACAN, similar to tankers when they are beeing controlled manually.

**Comment by 132nd-Entropy** [comment]
I think at this point it should be clear that we put the AIRBOSS back in really. None of the claims regarding performance loss etc could be backed up. We can't ask from hosts to always manually update both  carriers and their waypoints when they change the weather.  The AIRBOSS would not interfere with any operations, if people dont like it, they don't have to use it.  Etcher is already working on a grading board etc, good stuff to come

**Comment by 132ndEvo** [comment]
I agree with entropy airboss is the way forward for the moment. But we need to establish a wing SOP. For example do we only use airboss to turn the carrier or use use it fully and only use DCS ATC to turn on the lights for CASE3 ops

**Comment by 132ndNeck** [comment]
I suggest to implement airboss again. For hosts to change the carrier everytime we change the wind is not practical in my oppion.

**Comment by 132nd-etcher** [comment]
I 100% agree with @132ndNeck. The Airboss will also enable other goodies for us, with extremely small to no inconvenience.

**Comment by 132nd-Entropy** [comment]
this can be closed, as it was adressed with the new navygroups script. Once/if @132nd-etcher is back, we will put the airboss back in so his wip scoreboard can be implemented
