### ISSUE TITLE
New FARP IVURO at grid DN19 (waypoint IVURO) + SEAD tasking for 696th Range 12 Western Coast

### ISSUE THREAD

**Issue by 132nd-Inigo** [132nd-vWing/ATRM#109]
Looking for your kind approval for two things:
1. New FARP IVURO at waypoint IVURO, GRID DN19, 
2. SEAD tasking Range 12 Western coast, GRID DP17

.miz file with FARP IVURO and the Range 12 West coast SEAD tasking: https://drive.google.com/file/d/1aWUDIl4yh2U5PfbGhgjJ1pVbF6Srge2Y/view?usp=sharing

FARP layout: https://imgur.com/Tg5UtQl
SEAD layout: https://imgur.com/Zn4xF1p

FARP units and statics have a prefix of FARP IVURO followed by [static/checkpoint/checkpoint N/units/overlook], spawn points are labeled "[airframe] Range 12". 6x Ka-50 slots (4 on FARP; 2 on ground), 2x Mi-8 slots on ground.

SEAD tasking group names are below. They are all labeled as late activation and are hidden. Only SA-6 site is not hidden:
R12_SEAD_Recce_1
R12_SEAD_Recce_2
R12_SEAD_SAM_1
R12_SEAD_SAM_2
R12_SEAD_SAM_3
R12_SEAD_ARMOR_1
R12_SEAD_ARMOR_2

**Comment by 132nd-etcher** [comment]
Due to the amount of edits, please take note of the commit you used as a base before editing (might be the ATRM version), so we can roll back to that one in case someone makes minor changes in between (it'll be easier to redo the minor changes on top of yours than the reverse).

Looking awesome by the way!

**Comment by 132nd-Entropy** [comment]
thanks, implemented!

**Comment by 132nd-Entropy** [comment]
[3:48 PM] 132nd.Inigo: @132nd.Entropy please add a script activating the Range 12 extra units noted in the post, under label "Activate Rotary SEAD scenario Range 12 Western Coast" under Range 12 options

**Comment by 132nd-Entropy** [comment]
completed. Range 12 menu entry created. 

menu item list updated 
https://github.com/132nd-vWing/ATRM/issues/94

needs to be included in the ATRM GH brief
