### ISSUE TITLE
Available emmergency Hot start slots (read the reasoning and use-case)

### ISSUE THREAD

**Issue by thebgpikester** [132nd-vWing/ATRM#11]
If everyone in the squadron wrote down times where someone in their flight or another you were working with was 

- Late
- Had a technical problem
- Was otherwise unable to join at the right time

We would have many legitimate reasons where a hot start or air start would have saved the other people that didn't have an issue, 10+ minutes of their training time.

This issue does not suggest using this becomes main stream, just that it provides an option that can correct a problem.

They can come with guidance and process. I.e. not to be used until a problem occurs and with some kind of justification, put in a specific place/lane outside of any Controlled area and even be mentioned/catered for in AAR's.

It's just a fact of life that things happen, people often have to rush back late from work and the smaller things like working out if Microsoft updates are due, software updates to any of the software we use, restarts etc, fall down on the list of things to do when catching up with the hectic MDC building, reading plans, making/eating dinner.

**Comment by 132nd-Entropy** [comment]
closing this issue as there was no feedback
