### ISSUE TITLE
request for approval: put in a red AWACS in the West, so red planes can have datalink picture

### ISSUE THREAD

**Issue by 132nd-Entropy** [132nd-vWing/ATRM#110]
request a spawnable Red Awacs south of Range 1, ideally in Range 2 airspace to support BVR training including red air

**Comment by 132ndNeck** [comment]
Makes sense to have one.
Can also add a extra carrier WEST of the map to support as aggressors

**Comment by 132nd-Entropy** [comment]
that would be cool. Shall we leave the EAST red carrier in, or simply relocate?

**Comment by 132ndNeck** [comment]
I see that the initial AWACS and carrier have simply been moved west, which mess up AWACS coverage for aggressors in Range 12 and down south in range 10/11.

I will move the carrier and red AWACS back to the EAST where they were and where they are intended for aggressors duties.

I suggest to rather create a new AWACS and Red Carrier in the WEST to support A-A operations as aggressors in the WEST.

**Comment by 132nd-Entropy** [comment]
rgr!
