### ISSUE TITLE
[Request] F10 spawnable intercept group MOA1

### ISSUE THREAD

**Issue by Noctrach** [132nd-vWing/ATRM#113]
For part of the 108th CT training we would like to focus on All-Weather Intercept tactics.
It would be extremely helpful for us if we could have an F10 (re)spawnable flight of passive Tu-22s or Su-24M "drones" come in from the West side of MOA1. Ideally at varying angles and altitudes.

The primary reason to use AI aircraft rather than practicing within the squadron would be related to flight size and multiship tactics. With 108th flying two-seat aircraft, we are generally limited on full crews. AWI requires heavy RIO-pilot interaction. Having drones would alleviate the need to split up flights into singletons and allow us to practice single-side offset, pincer and trail intercepts. It would also improve training efficiency by not requiring one side to act as purely passive targets.

If approved, Entropy would be able to assist me in properly implementing this into the mission file.

**Comment by 132ndNeck** [comment]
I am happy with it.
If placed at the WESTERN part of MOA 1, and make sure it never flies out of MOA 1 (never EAST of MOA 1)
Then it can be used (can also have different types of aircraft and also armed as long as effects and the aircrafts are within MOA 1 only.

**Comment by 132nd-Entropy** [comment]
Copy, on it!

**Comment by 132nd-Entropy** [comment]
ok request some help here @Noctrach 
can you please design the framework, how exactly you want to have it implemented, then Im happy to do the coding. 

for example, have templates in the mission file with teh desired loadouts and skins (late activated),  and state their groupnames here, I can from those make a table and draw randomly to spawn one of them.

Then set some late-activated planes and draw trheir waypoints ( or zones in which they should fly) etc. then also give me what menus you wnat for trigger what. 

its easier if peopel tell me how they want it, so I can do it, instead of me guessing it and then having to change it ;)

**Comment by Noctrach** [comment]
> 
> 
> ok request some help here @Noctrach
> can you please design the framework, how exactly you want to have it implemented, then Im happy to do the coding.
> 
> for example, have templates in the mission file with teh desired loadouts and skins (late activated), and state their groupnames here, I can from those make a table and draw randomly to spawn one of them.
> 
> Then set some late-activated planes and draw trheir waypoints ( or zones in which they should fly) etc. then also give me what menus you wnat for trigger what.
> 
> its easier if peopel tell me how they want it, so I can do it, instead of me guessing it and then having to change it ;)

For sure :D I'm happy to help as well.

The idea was:
- Two or three F10 menu options to spawn a 2-ship of Su-24M/Tu-22M/Tu-95s. (Loadouts optional, would be a "nice to have")
- Targets set to defend in the usual ways but absolutely passive.
- Respawnable if shot down.
Spawn parameters would be:
- **Required:** Western edge of MOA1, flying a racetrack pattern west-to-east, turning back at around 2/3rd the range
- **Nice to have:** Variable altitude and heading.

Ping me in discord if you have any futher questions.

**Comment by 132nd-Entropy** [comment]
This is implemented now, here is how it works: 

![image](https://user-images.githubusercontent.com/19779428/107363932-1c4b2180-6adb-11eb-9d06-0ecd29462165.png)

in red is MOA1
in white is the 'engage zone'

red Mig29s (singletons) will be spawned whenever one chooses the menu command. 

they will set up a E-W Racetrack  (15nm) at the WEST of MOA1

they will engage when those criteria are met: 

1. the target is actually detected by the red mig29s
AND
2. the target is inside the (white) patrol zone
AND
3. the target is within 60nm of the MIG

a menu option exists also to instantly destroy all redair in moa1
