### ISSUE TITLE
Range 14 preset CAS scenarios - only 1 out of the 2 is working

### ISSUE THREAD

**Issue by IAFAssafB** [132nd-vWing/ATRM#115]
Trying the preset-CAS-scenarios in range-14.
Only R14 CAS Scenario 1 is actually being activated, even when trying F5 for scenario "2".

I think (Warning, MOOSE-noob here!) that in ATRM_Range_14.lua line 182 should be

trigger.action.setUserFlag(112, true )
and not
trigger.action.setUserFlag(111, true )

Thanks!

**Comment by 132nd-Entropy** [comment]
sounds like an easy fix! :D

**Comment by 132nd-Entropy** [comment]
fixed
