### ISSUE TITLE
Request to add a menu item for activating basic CAS scenario at Range-14

### ISSUE THREAD

**Issue by IAFAssafB** [132nd-vWing/ATRM#116]
Should read something like
"Range 14 Basic CAS scenario"
And trigger flag 113.

Thanks!

**Comment by 132nd-Entropy** [comment]
hi, this is done. Can you please add this and the other scenarios you made to

 https://github.com/132nd-vWing/ATRM/issues/90

and 

https://github.com/132nd-vWing/ATRM/issues/94

**Comment by IAFAssafB** [comment]
Thanks buddy! Done.

**Comment by 132nd-Entropy** [comment]
there is no description of what the 
"Activate Range-14 preset CAS scenario 1"
"Activate Range-14 preset CAS scenario 2"

do in the ATRM brief entry for Range 14

**Comment by IAFAssafB** [comment]
Done.
(Well, I think anyway :-) )
