### ISSUE TITLE
CVN 71 RED Carrier issues 17FEB2021

### ISSUE THREAD

**Issue by 132ndThumper** [132nd-vWing/ATRM#117]
During ATRM, Wednesday February 17th we spawned in Red Aircraft on the carrier CVN 71 and made the following observations:

- The TACAN 71X did not pick up anything
- Air Boss was not available (maybe that's due to having it on the blue carrier?)
- The carrier stopped moving with a crosswind :-D

Hope this report helps!
Thanks guys, as always.

**Comment by 132nd-Entropy** [comment]
hey, yeah, we wanted to give the airboss a good test on the blue carrier before implementing it on the red one, so its simply not installed yet. Will do so asap now. as always, thanks for feedback!

**Comment by 132nd-Entropy** [comment]
should be done
