### ISSUE TITLE
Enemy shipping range

### ISSUE THREAD

**Issue by thebgpikester** [132nd-vWing/ATRM#12]
With the advent of the AGM-84 Harpoon, and the availability of open sea, Anti Shipping missions have barely been touched in 132nd. I'd like to see this, personally, i'm sure the 494th would.

**Comment by 132Ashilta** [comment]
I think the opportunity to provide a mechanism for this would be of incredible use for advance training - a couple of aggressor flights, one anti-ship with an escort, allows for a real scenario to be played out and drive good coordination towards a common objective. Such training would be particularly supportive of our requirements for package integration in OPUF.

**Comment by 132ndNeck** [comment]
I fully support this, and it will be included

**Comment by 132ndNeck** [comment]
In place in range 1.
