### ISSUE TITLE
Invincible A-10c II

### ISSUE THREAD

**Issue by 132nd-FurFace** [132nd-vWing/ATRM#120]
Request that 2 invincible A-10c II’s be made available in the ATRM.  

Whilst practice missile avoidance was hit by a SAM and aircraft was destroyed.

**Comment by steven-omaha** [comment]
I would convert the remaining old-gen A-10C in the map to A-10C II. In that process I would set 4 in OMAM to invincible, and 2 in each of the other airfields. I would adjust the group names correspondingly.

**Comment by 132nd-Entropy** [comment]
I think that would be a good idea!

**Comment by steven-omaha** [comment]
implemented in b70de19
