### ISSUE TITLE
SA-15 at Ras Al Kaimah default active and hidden

### ISSUE THREAD

**Issue by steven-omaha** [132nd-vWing/ATRM#124]
In today's CAS training, both flights were suddenly engaged by an SA-15 that is apparently located as Ras Al Kaimah.  I tried disabling it from a Game Master slot, but it was hidden.

It is my understanding that red SAM sites default to OFF unless activated? In any way, the page for Range 12 does not mention SAMs that are active by default. https://132nd-vwing.github.io/ATRM_Brief/Ranges/Range12.html

**Comment by 132nd-Entropy** [comment]
@132ndNeck is this one for you ?

**Comment by 132nd-FurFace** [comment]
Should the SA-15 become active when Range 12 AR scenario activated?  We were engaged several times during last nights training from the SA-15 at Ras Al Kaimiah. It was not activated via the F10 menu.

**Comment by 132nd-Entropy** [comment]
fixed
