### ISSUE TITLE
MOA1 MiG-29s spawn point displacement 

### ISSUE THREAD

**Issue by 132ndTB** [132nd-vWing/ATRM#125]
While spawning AI MiG-29s in MOA1 they are at the same spot, and since they are in 40-50 miles from you when you are in the trigger zone they don’t represent a formation, rather a beehive. If they would spawn 5-10 miles apart then activating them we could get a line abreast of enemies, and later activating the second element can give a 4-ship box formation. That way sorting and targeting can practiced better hence formation management for our training.

**Comment by 132ndEvo** [comment]
I think a 2 ship option and a 4 ship option would be best. Since we usually enter from the east, they can spawn 60 miles away, creating a good distance for a timeline.

**Comment by 132nd-Entropy** [comment]
hey, you mean they should spawn 60 miles away from the Eastern border of MOA 1? or the western border?

**Comment by 132ndEvo** [comment]
I was thinking they should spawn 70 nm from the eastern border. So when you enter from the east you can begin a timeline.

**Comment by 132nd-Entropy** [comment]
ok

**Comment by 132nd-Entropy** [comment]
implemented in ATRM 2.7
