### ISSUE TITLE
Request KC-135 track by MOA1 / Range 1

### ISSUE THREAD

**Issue by hbjonsson** [132nd-vWing/ATRM#127]
For convenience sake it would be good to have a KC135 tanker by Range 1 / MOA1. Could be at same place as AR304.
For variety, FL240 would be nice / ( M0.7 )

**Comment by 132nd-Entropy** [comment]
Hi as Neck is not here to approve or not, at the moment id say we do this. Put in the tanker where you need it, set to late activation choose a frequency, tacan, name, iff code and let me know so I can add it to the script. Also make sure to update the ATRM brief with the info

**Comment by 132nd-Entropy** [comment]
implemented
