### ISSUE TITLE
"GFC Brief" from R14 CAS presets is visible to all players instead of only JTACs

### ISSUE THREAD

**Issue by IAFAssafB** [132nd-vWing/ATRM#128]
The brief message should be hidden to pilots.

**Comment by IAFAssafB** [comment]
Changed all JTAC units in R14 to "Switzerland" country and all the messages directed for that country (Was USA, which is just like all other airframes)
Additionally, adjusted the phrasing of the messages regarding to R14 preset CAS scenario (Shortened from "Activate Range-14 preset CAS scenario x" to "Activate R14 preset CAS scenario x". This way the messages in the menu are 1-liners and easier to read.
The corrected miz is uploaded to the ATRM_Github channel with name : ATRM_2.7.0.440_fixed_R14_msg 
Need someone to put it into the repo as I don't have it available from my side (Noob, yep).

**Comment by steven-omaha** [comment]
fixed in 79ad3a6
