### ISSUE TITLE
AR204 frequency (152.0) is un-tunable by F-16´s ( max is 151.950 )

### ISSUE THREAD

**Issue by hbjonsson** [132nd-vWing/ATRM#129]
As per the title.

Suggest 138.0 which should be free according to this : https://132nd-vwing.github.io/ATRM_Brief/Pages/Tanker.html

does not affect ATRM_Tankers.lua

**Comment by hbjonsson** [comment]
Would be good to get this fixed before tomorrow, so that AR204 is at least usable :-)

**Comment by steven-omaha** [comment]
Should be good. Please 
* verify using https://132nd-vwing.github.io/ATRM_Brief/Pages/Presets.html that 138.0 is available and not in use for anything else.
* update the miz and the corresponding info in ATRM_Brief 
* create a PR in both repos
