### ISSUE TITLE
Ability to restrict missile script to certain zones?

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/ATRM#13]
Is it possible to restrict the missile script to certain zones?
For example having it enabled over Ranges, but not over IRAN?

Looking at the overall scenario, and using a combination of OPUF and this new training mission  ( with static templates it is easy to add stuff and transform this mission into a combat event on short notice, and with minimum effort.

But it would require the missile script to be able to work in only some zones.

@132nd-Entropy Do you know this?

**Comment by thebgpikester** [comment]
it does do this, but I haven't tested it. I think Entropy accidentally tested it early on.
https://flightcontrol-master.github.io/MOOSE_DOCS_DEVELOP/Documentation/Functional.FOX.html 
```fox:AddSafeZone(ZONE:New("Training Zone Alpha"))```

**Comment by 132nd-Entropy** [comment]
works yes, but the question is,  I think we need to stop using the missile script, as it's not reliable?
