### ISSUE TITLE
New IADS Range

### ISSUE THREAD

**Issue by 132ndEvo** [132nd-vWing/ATRM#131]
Hey Everyone, 
I would like to make a new range in the north in Iran. The range would have to be far away because I intend on making an SA-10 IADS network for SEAD, DEAD, AI, SWEEP, and package training. It is a major task to add a range so I wanted to get everyone's opinion. Thanks

**Comment by 132nd-Professor** [comment]
Setting to approved.

**Comment by 132nd-Professor** [comment]
In 31566ae you added `mist_4_4_90.lua`. We already had a `mist_4_3_74.lua` in ATRM, and it is still there. 

I would expect this to lead to compatibility issues. Could the old mist be removed?

**Comment by 132ndEvo** [comment]
Hi professor I removed the older mist and added the latest one since the older one was giving issues with skynet. There should not be any reference to the older one.

**Comment by 132nd-Professor** [comment]
Thanks! Then I would recommend simply deleting  `ATRM/l10n/DEFAULT/mist_4_4_90.lua` in a new commit.

**Comment by 132nd-Professor** [comment]
Thanks! Then I would recommend simply deleting  `ATRM/l10n/DEFAULT/mist_4_3_74.lua` in a new commit.

**Comment by 132ndEvo** [comment]
Ahh I see, ok I'll do that now thanks for reminding me

**Comment by 132nd-Professor** [comment]
Can this be closed?

**Comment by 132ndEvo** [comment]
Sure I’ll keep updating it though
