### ISSUE TITLE
Establishing SIDs and STARs

### ISSUE THREAD

**Issue by steven-omaha** [132nd-vWing/ATRM#14]
Would be a great addition if we could have SIDs and STARs for the most relevant airbases. Maybe begin with Al Dhafra.

**Comment by 132nd-Entropy** [comment]
we do have that, check ATRM briefing there are IFR and VFR procedures. can this be closed?

**Comment by steven-omaha** [comment]
Can be closed. Thanks. (Can't do it on mobile app)
