### ISSUE TITLE
Range-14: When activating "basic CAS scenario" the wrong message is displayed

### ISSUE THREAD

**Issue by IAFAssafB** [132nd-vWing/ATRM#141]
In Range-14, when activating "Basic CAS scenario" from the F10 menu, a message pops stating "CAS scenario 2 activated" (Whereas the correct message should be "Basic CAS scenario activated"

I suspect I introduced it when adding one of the recent new CAS-preset scenarios and edited the MOOSE file of Range-14. This is likely to be an issue with other scenarios as well.
It should be noted that the Basic-CAS scenario that was requested was indeed the one that was activated so it's only the message that's wrong.
Will try to get to it and address it this week.

**Comment by 132nd-Entropy** [comment]
this was fixed but not marked as resolved
