### ISSUE TITLE
Live SAMs interfering with training IVO R15

### ISSUE THREAD

**Issue by IAFAssafB** [132nd-vWing/ATRM#145]
In R15 there are two SAM groups:
R7_31st_SA13_2
R7_31st_SA13_1
That are NOT set as LATE ACTIVATION although I think perhaps they should be. Those RED groups are alive and firing.
Not sure if/how they are linked to any range/scenario so not touching in fear I'll break something...

**Comment by 132nd-Entropy** [comment]
I think they should be late-activated, fixed
