### ISSUE TITLE
Access to Range 2

### ISSUE THREAD

**Issue by Ravasempai** [132nd-vWing/ATRM#146]
Is it possible to narrow Range 1 a small amount and put in a corridor to range 2.
We had issues crossing a few times from the carrier when Range one has been in use. 
It does not need ot be big but atleast something we can pass though with out issue.

Secondly, With range 2, it is a VERY long distance to AR403 to refuel and with Range one being there it makes it even more challenging for Fuel management.
Is it possible to change the bearling of AR304 to North South at edge of Range One to allow easy access to anyone on the other side.

Range 2 feels really inaccessable at the moment and I think these suggestions may help

**Comment by 132nd-Entropy** [comment]
It can all be done, but I'd require updating also the ATRM Briefing pages, any pictures etc etc. thats quite some work, but if anyone volunteers, go for it

**Comment by 132nd-Entropy** [comment]
not sure how to proceed here, I think its maybe not worth the investment, but if anyone wants to step up and do this, by all means go ahead
