### ISSUE TITLE
More than one training scenario may be activated in one range, causing a mess

### ISSUE THREAD

**Issue by IAFAssafB** [132nd-vWing/ATRM#149]
It would seem that more than one training scenario may be activated via the OTHERS menu for a specific range.
This may result in a scenario being activated by mistake of someone AFTER a "correct" scenario has already been activated for the specific range. Thereby adding additional units "not supposed to be there" and confusing the players of the intended scenario.

1. Activate RANGE-15 CAS-preset-scenario#2
2. Activate AR SCUD HUNT BLUE 
3. Resulting in units of the two scenarios present

**Expected behavior**
I recall in the past that whenever one scenario was activated, the menu for the same range would be deactivated so that no additional actions may be done for that range. I suspect at least a few of the CAS scenarios I added to the ATRM (R15, R14, R16) somehow lack this extra action of removing the menu.

With my next-to-null knowledge of MOOSE / LUA it'll take me ages to go over the MIZ and correct those (And unlikely to do so without breaking other stuff in the way...). 
I therefore humbly ask that if anyone fluent with how the ranges/menus are built would go over them and make those menus go dark as they should be :-)

**Comment by 132nd-Entropy** [comment]
this is fixed, but was not marked as resolved
