### ISSUE TITLE
REQ HELP:  Tanker and AWACS orbits

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/ATRM#15]
Ok, I have now added AWACS and Tankers to the .miz.
What is currently in the .miz is what I would like their orbits to be.

Also, as @daviddcs mentioned in Issue #7 , the idea is not to have all of these up all the time, but beeing able to request what you need for a certain event. 

On a normal event, the following tracks should be active:

AWACS: MAGIC
Tanker: 
AR201 - For Vipers
AR301 - For Hornets and Tomcats
(So only blue assets, as aggressors assets is then requested if needed , to reduce strain on the server)

I am not sure how to do this in a good way, but then have a possibility for activating a new tanker or AWACS, and also to deactivate on of the tracks in action. 

All AWACS and Tankers should start at:
BLUE: Dubai International
RED: Sharjah Intl
Tankers should follows corridors or stay outside range airspace during transit

Detailed information
TANKERS BLUE
AR101: KC-135, Tacan 38X. Freq: 150.0, FL120

AR201: KC-135, Tacan 39X. Freq: 151.0, FL200

AR301: KC-135 MPRS, Tacan 40Y. Freq: 152.0, FL240
AR302: KC-135 MPRS, Tacan 41Y. Freq: 153.0, FL240
AR303: KC-135 MPRS, Tacan 42Y. Freq: 154.0, FL240
AR304: KC-135 MPRS, Tacan 46Y. Freq: 158.0, FL240

TANKERS RED
AR401 KC-135 MPRS, TACAN 43Y. Freq: 155.0, FL230
AR402 KC-135, TACAN 44X. Freq: 156.0, FL200
AR403 KC-135, TACAN 45X. Freq: 157.0, FL200
AR404 KC-135 MPRS, TACAN 47Y. Freq: 159.0, FL230

AWACS
AWACS BLUE
MAGIC: Freq:305.0, FL400
DARKSTAR: Freq: 306.9, FL390

AWACS RED
FOCUS: Freq: 307.0, FL400

Extra: IF POSSIBLE:
Have a way of moving AR101 into AR201. If that works, then one of them can be moved, and players can simply fix it themself.

Reference Issue #7

**Comment by 132nd-Entropy** [comment]
completed

**Comment by 132ndNeck** [comment]
Issue with the AWACS, they RTB and do not stay in the orbit.

**Comment by 132ndNeck** [comment]
**TANKER REQUEST 1**
In addition to AWACS mentioned above, would it also be possible to add the following:

AR202: KC-135, Tacan 48X. Freq: 141.0, FL200
AC is already in the .miz as late activated (ARCO AR 202).

Should be activated on request (F10 menu)


**TANKER REQUEST 2**
Could AR101 (Texaco AR 101 #IFF5314FR) be set to on request (The A-10s dont refuel as much as the Viper, Tomcats and Hornets, so it can be on request)

**Comment by 132nd-Entropy** [comment]
> Issue with the AWACS, they RTB and do not stay in the orbit.
> 
> Reopened

that's because there is no orbit set in the ME

**Comment by 132nd-Entropy** [comment]
fixed now

**Comment by 132nd-Entropy** [comment]
> **TANKER REQUEST 1**
> In addition to AWACS mentioned above, would it also be possible to add the following:
> 
> AR202: KC-135, Tacan 48X. Freq: 141.0, FL200
> AC is already in the .miz as late activated (ARCO AR 202).
> 
> Should be activated on request (F10 menu)
> 
> **TANKER REQUEST 2**
> Could AR101 (Texaco AR 101 #IFF5314FR) be set to on request (The A-10s dont refuel as much as the Viper, Tomcats and Hornets, so it can be on request)

AR202 - done
AR101 - was on request spawning already?

**Comment by 132ndNeck** [comment]
@132nd-Entropy 
Can we update and make all tanker tracks deactivated?
Currently we have the following always active:
AR201 - For Vipers
AR301 - For Hornets and Tomcats

But can they be set to deactivated and beeing activated via F10 as the rest of the tankers?
This to 1. reduce strain on server when they are not needed and 2. Remove issues for Range 9 when they are not needed.

**Comment by 132nd-Entropy** [comment]
done!
