### ISSUE TITLE
Air-to-Air AI in MOA1

### ISSUE THREAD

**Issue by MatteoN74** [132nd-vWing/ATRM#150]
Hi, Waze here. It would be really great for Air-to-Air training to expand the options available to spawn AI targets in MOA1 to diversify Air-to-Air training. Happy to work on this with the designer.

Ideally, there should be 6 serial submenus:
1. Type of aircraft (at a minimum civilian liner or transport, helicopter, GEN3 threat like Mig21/23, GEN4 like Mig29 with AA10A + AA11, GEN4+ like SU35 with AA10C/AA12 + AA11)
2. Number of aircraft
3. Type of formation (to include azimuth and range presentation of multiple groups)
4. Altitude (Low, medium, high)
5. Spawn location (East or West side)
6. AI (dumb, aware, threatening)

**Comment by 132nd-Entropy** [comment]
if someone has time to take this on, I'd be happy to assist with the scripting. first thing would be to place the units, state their groupnames and set them to late activation
