### ISSUE TITLE
Add naval task force/convoy 

### ISSUE THREAD

**Issue by 132ndArtur** [132nd-vWing/ATRM#152]
For future MCC operations I request creating REDFOR naval task force or heavily protected convoy spawned on demand to practice Anti Ship Warfare.

Due to high destroyers and frigates engagement range I suggest placing the group on far North-western or East side of the map. 

REDFOR Naval group/convoy should contain at least:
2x Destroyers
2x Frigates
2x cargo ships

**Comment by 132nd-Entropy** [comment]
Hi @132ndArtur sure! I suggest you edit the latest ATRM build, place the unit GROUP names here and set them to late activation. Based on the group name I can then write the script to spawn them, please include any options you want to have, ranomization of spawns, randomization or routes etc.

**Comment by 132nd-Entropy** [comment]
closing this as there was no more progress. suggest we implement this in the new training mission
