### ISSUE TITLE
REQ HELP: Add missile script

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/ATRM#23]
Request to add the missile script to the .miz so that we can start firing A-A missiles.

**Comment by 132nd-Entropy** [comment]
I think we need to stop using it, as it's not reliable?

**Comment by 132ndNeck** [comment]
I suggest we use it, but add invulnerable AC (especially for A-A aircrafts)
This to support for getting notifications from the script.
Can be good for SEAD practice, evasiuve practice, and basic A-A practice (but invunlerable AC in case the script fails)

**Comment by 132nd-Entropy** [comment]
rgr!

**Comment by 132nd-Entropy** [comment]
done
