### ISSUE TITLE
REQ HELP: Range 10 IADS - Scenariotraining

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/ATRM#24]
In support of scenariotraining in Range 10, I request the following IADS function.
The function should be availeble via the F10 menu.

In Range 10, (south part) there are 1 EWR, 3 threat sites and 1 mobile threat site.

- Threatsite_1 
- Threatsite_2
- Threatsite_3
- Threatsite_4_mobile
- Threatsite_EWR

The 4 threatsites is protecting a target area.  The intention is to have the IADS protecting the high value target, and having options to conduct AI strikes against this target either with IADS off, IADS easy , IADS medium or IADS hard  ( to have options to include SEAD element or simply practice SEAD)

**IADS Easy:**  Randomly select 2 of the 4 threatsites and let them be on all the time.

**IADS Medium:** Randomly select 3 of the 4 threatsites to be on.
When a HARM is fired at any of the sites: shut down the radar on that threatsite. (
Random delay of 3-8 seconds after launch of the HARM trigger the activity (To simulate they actually beeing able to detect the missile before moving)
Let the radar be off in a random interval between 60-180 seconds.

**IADS Hard:** All 4 sites are in play
Only EWR is on initially. Once EWR detetcts a contact within the zone: R10_EWR  it turns on Threatsite_1. 

If a HARM is launched at Threatsite_1 or Threatsite_EWR then all other threat sites is activated aswell. Threatsite_2  , 3 and 4.

When a HARM is fired at any of the sites: shut down the radar on that threatsite.
Random delay of 3-8 seconds after launch of the HARM trigger the activity (To simulate they actually beeing able to detect the missile before moving)
Let the radar be off in a random interval between 60-180 seconds.

(For reference: Issue #1 )

**Comment by 132nd-Entropy** [comment]
completed, testing required, especially for IADS hard

**Comment by 132ndNeck** [comment]
Tested now. Flew an F16, cold start from Al Dahfra. IADS hard.
EWR is on (so is search radars from the SA2 and 3 sites)


But the EWR never picks me up, although I fly high and within his LOS above the targets. 

So, get no reaction from the site. Similar to what Kimkiller and Teddy experienced the other day.

**Comment by 132nd-Entropy** [comment]
I only tested by placing an F18 in the ME in the air and fly towards the area. it picks me up and the TS1 engages, like planned. I don't think there is anything I can do in the scripting environment, as I don't see an 'error'

**Comment by 132ndNeck** [comment]
I tested now on the server, in  F16 which was a single group (so not in a group with multiple aircraft like before).

Still no effect unfortuantly, so looks more to be a bug with MP, that causes it not to work

**Comment by 132ndNeck** [comment]
Is it possible to have a F10 menu option to deactivate the IADS?

**Comment by 132nd-Entropy** [comment]
done, IADS can be disabled now
