### ISSUE TITLE
REQ HELP: Adding carriers (Blue+Red)

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/ATRM#28]
Would it be possible to add carrier script to the following carriers:
**BLUE**
CVN-74
TACAN 74X

**RED**
CVN-68
TACAN 68X

Carriers are in the .miz already in their area. So can setup a racetrack in that position
(But do not add any rescue helicopter or statics on deck, should be as clean as possible)

If possible, have a Carrier tanker as a F10 option to launch if needed (but not airborne by default)

Freqs:
![bilde](https://user-images.githubusercontent.com/26002570/67581056-a1c08c00-f747-11e9-9ebc-03367825eb45.png)

**Comment by 132nd-Entropy** [comment]
rgr. need tanker freqs and tacan

**Comment by 132nd-Entropy** [comment]
also, in the TRM we merged tower and LSO, you sure you dont want to do this here also ?

**Comment by 132ndNeck** [comment]
Yes, good point. We should merge TWR and LSO.  But have AI TWR on a seperate freq?

**Comment by 132ndNeck** [comment]
-- | -- | --
Recovery tanker Stennis | 142.5 | 48Y
-- | -- | --
Recovery   Tanker nimitz | 143.5 | 49Y

Both Callsign SHELL

**Comment by 132nd-Entropy** [comment]
have to use rescue helo as radio relay, but the carrier scripts should be working now
