### ISSUE TITLE
A-A drone range

### ISSUE THREAD

**Issue by 132ndSpiff** [132nd-vWing/ATRM#3]
A basic air-to-air training range, with drones flying known and predictable circular and/ or racetrack patterns in order to practice procedures and weapons in a permissive environment.

- Radar mechanics
- Intercepts, sorts, melds etc
- Missile shots
- Gunnery

**Comment by 132ndNeck** [comment]
Do we need this?

Also see Issue #2 

We will have tankers and AWACS AC flying, so if it is only to see something on the radar and do intercepts, that should be doable against them?
If it is to practice shoothing then the singleplayer training missions is sufficient?

**Comment by 132nd-Entropy** [comment]
this looks to be rejected, closing this issue
