### ISSUE TITLE
REQ HELP: Range 14 - Dynamic CAS Range - SAMs for complexity

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/ATRM#30]
Is it possible to add the following to the Range 14 Cas Scenario:
Add a option to run CAS scenario with SAM or without SAM.

(with SAM's CAS flights may need to use Low-level procedures)

If choosing to run with SAM, then one of the following SAMs will be activated: (currently in place, but set as late activated)
Threat_site_13
Threat_site_14
Threat_site_15

This is linked to Issue #29

**Comment by 132ndNeck** [comment]
This works great, but we will need to adjust the spawn speed. I am reopening this, but I do not have a correct value yet. Will need to try once with a JTAC doing CAS.

Hansolo and Kimkiller tested and it worked well.

**Comment by 132nd-Entropy** [comment]
Glad to hear! The times can be changed super easily
