### ISSUE TITLE
REQ HELP: Range 13  - Basic Range script options

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/ATRM#31]
I request some assistance to get range 13 setup as a basic range like range 10 on TRM.
Targets are already in place.

**Comment by 132nd-Entropy** [comment]
done

**Comment by 132nd-Entropy** [comment]
Added Range Instructor and Range Control VoiceOvers to the RANGE 4 and RANGE 13 VHF frequencies. request testing
