### ISSUE TITLE
S3 Viking tanker at Stennis - no published frequency

### ISSUE THREAD

**Issue by evilivan** [132nd-vWing/ATRM#35]
We tuned TACAN to the Viking at the Stennis on 48Y, but couldn't find a published frequency to match that TACAN station.

**Comment by 132ndNeck** [comment]
![bilde](https://user-images.githubusercontent.com/26002570/67904718-830b2c80-fb6f-11e9-940a-3fad23aedea4.png)

**Comment by evilivan** [comment]
Dammit - I thought I'd checked that thoroughly; cleared not. Thanks Neck.
