### ISSUE TITLE
Deep AR missions 

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/ATRM#4]
Deep AR missions for the A-10 hunting armour, SCUD's which would involve more flight planning, dodging/evading certain areas etc. Something like the first mission of Green Sword or strike done in range 4B comning in from the corridor. This  would give more to the flight planning for A-10C pilots

**Comment by 132ndNeck** [comment]
Created first version in Range 12.

Need to add randomization, but this works for now.

**Comment by 132ndHansolo** [comment]
Test observations.

Entered R12 **without** activating anything, e.g. only on the freshly started server. The list of active threat sites in R12 was **None**.

Flying into area around T12.9 I had following DIRT’s
FF	        Fujariah
SA-15	Ras Al Khaimah
SA-15	Wab Al Sebl
SA-15	Khasab

During flying in the area got MUD;
SA-15	Wab Al Sebl
SA-15	Khasab
Manpad	N25º 55.585  E056º 17.697


After **activation** of  R12, Armed Recce AIDS Medium, the list of active threat sites in R12 was **None**.
