### ISSUE TITLE
REQ HELP: Add on/off functionality for Blue SAM at Al Dahfra

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/ATRM#41]
At Al Dahfra there is now placed a BLUE SAM, a patriot batter for advanced training scenarios.

Is it possible to add a on/off function in the F10 menu. So it can be turned on and off
(so it can be turned off after exercise, so red ac can recover at Al Dahfra to maximise traffic.)

The Group is already in the .miz with the following name:AL_DAHFRA_PATRIOT

**Comment by 132ndNeck** [comment]
Would it be possible to have this as default OFF.
And turn on using F10

(Now it is on from start, but can be turned off)

Reason is that it is mostly needed for bigger scenario exercises, which we run not so often, so better to have it off to not drain the server unnecessary.

**Comment by 132ndNeck** [comment]
Bumping this one.

**Comment by 132nd-Entropy** [comment]
on it
