### ISSUE TITLE
redistribution of tankers

### ISSUE THREAD

**Issue by steven-omaha** [132nd-vWing/ATRM#44]
from http://132virtualwing.org/index.php/page/event_debrief?id=1089

It would be great if there would be another tanker further away from Al Dhafra. In the Hawgs, we were pretty far away at T10.1.

**Comment by 132nd-Entropy** [comment]
should this be implemented?

**Comment by steven-omaha** [comment]
I have to say, this was after training threat management for the first time at Range 10. Range 2, which we use now for that, wasn't available back then. Nevertheless, the Hawgs have exactly one usable tanker right now.

**Comment by 132ndNeck** [comment]
@steven-omaha 
Do the 617th  need more than one tanker? If yes, where should it be placed?

I prefer not add stuff to the missions that are not used. But if it is needed it is of course not an issue to add it.

**Comment by steven-omaha** [comment]
With the availability of Range 2 and Al Ain, we currently do not need a tanker.  This issue would come up again should we decide to train on range 12. This is the consensus from discord. Can be closed for now.

**Comment by 132nd-Entropy** [comment]
oki
