### ISSUE TITLE
REQ HELP: Range 12 - SAM / IADS

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/ATRM#47]
@132nd-Entropy Would it be possible to add a menu option to turn on the SAMs now in place at range 12?

Range 12 is inteded as a scenario range (have option for scenario). For that having the ability to turn on one or more of the 4 static SAM systems would be beneficial. If possible having an option for a easy, medium and hard for each SAM.

Requested functions:
- Ability to activate (and deactivate each threat site individually)
- Ability to use different difficulty levels on the SAM sites

**Difficutly level:**
**Easy:** SAM is always on (after beeing activated), and do not react to beeing shot at.
**Medium:** SAM is always on (after beeing activated) until fired upon by HARM. When a HARM is fired at the site, the radar shut down on the threat site. Random delay of 3-9 seconds after launch of HARM before the site shuts down.  Let the radar be off in a random interval between 60-180 seconds before active again.
**Hard:** After activation, SAM is on in random intervals between 60-200 seconds. Then it is off in random intervals between 60-200 seconds. . When a HARM is fired at the site, the radar shut down on the threat site. Random delay of 3-9 seconds after launch of HARM before the radars shuts down. Move the group a random interval between 30-100m in any direction. Let the radar be off in a random interval between 60-180 seconds before active again.

When a HARM is fired at any of the sites: shut down the radar on that threatsite. (
Random delay of 3-8 seconds after launch of the HARM trigger the activity (To simulate they actually beeing able to detect the missile before moving)
Let the radar be off in a random interval between 60-180 seconds.

**SAMs:**
Names in the ME
Threatsite_12_1  
Threatsite_12_2  
Threatsite_12_3  
Threatsite_12_4    
Threatsite_12_5    

**Explanation:**
Threatsite_12_1   : SA-3
Threatsite_12_2   : SA-11 
Threatsite_12_3   :  SA-2
Threatsite_12_4  : SA-6 
Threatsite_12_5  : SA-8

**Comment by 132nd-Entropy** [comment]
completed, with the following changes: 
- IADS medium or hard can be only requested once, and for all active sams (not individual sams)
- on/off cycle on IADS hard is a fixed 120 sec (not random, as this is in this case is more complicated)

**Comment by 132ndNeck** [comment]
Have tested this a few times now, a couple of suggestions:

- HARD IADS: Right now I think all SAMs are on / off at the same time? Is it possible to make this different, so the various SAMs are on at different times?
- HARD/MEDIUM IADS: Is it possible to add a function to turn off the IADS ?

**Comment by 132nd-Entropy** [comment]
changed HARD IAS so that the SAMs wont blink at the same time, as requested. 
also added IADS off function, but I Cannot for the sake of it figure out how to stop the Scheduler that makes them blink the radar on/off. So at this time, when IADS hard is disabled, they continue blinking Im afraid. need to think about this more

**Comment by 132nd-Entropy** [comment]
solved it, working as requested now I think.
