### ISSUE TITLE
Range 6 - Development-Ideas

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/ATRM#49]
**Suggestions for Range 6:**

- Create a "GREEN ZONE" in the urban area
- Add a FARP
- Create a FOB (for convoys moving between green zone and FOB)
- Add FARP at the FOB?

- Dynamic targets / randomization

- Convoy escort (With JTAC and without JTAC)
- Different Convoys /Different routes

**Comment by 132ndJunior** [comment]
- If FARP then definately within the FOB with 2-4 landing pads. (Al Ain is 13min away from Range 6 so no spawns on FARP are required)
- Add infantry to APCs (3-4 men plus MANPAD on occasion?)
- Communication with the convoy to order stop/move
- a mortar team target barraging an intersection and preventing convoy from crossing it?
- L shaped ambush with attackers from two directions

**Comment by 132nd-Entropy** [comment]
happy to work on this once a consent has been reached
