### ISSUE TITLE
REQ HELP: Fix TACAN errors

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/ATRM#54]
@132nd-Entropy 
I have looked through the TACANs based on the reporting in Issue #48 

There are a couple errors, so I request help from you to fix it in the script and change the TACANs for the following tankers:  (I assume it should only be set in the script?)

Recovery tanker Stennis:  64Y
Recovery tanker Nimitz: 65Y
AR305 (Shell): 37Y

**Comment by 132nd-Entropy** [comment]
neg, Tacans are not set via Script but via ME

**Comment by 132nd-Entropy** [comment]
sry,  recoveery tankers are set via Script
