### ISSUE TITLE
REQ HELP: Range 9 / EX GREEN STORM

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/ATRM#55]
For EX Green Storm I have created a tasking for AR in the desert.
(Link: https://132nd-vwing.github.io/ATRM_Brief/Pages/R9_AR_Desert_TASK.html )
This taskings uses a full motorized regiment (so many units)

In the .miz I have set all these groups now as late activated, and in the trigger list, I have created a trigger with condition Flag is true 100, then all groups activate.

**Requested feature 1:**
Add a F10 menu which says: EXGS - Activate AR R9
Once this is pressed, it set Flag 100 to true.

(So the groups will be activated. If you prefer to manually script them to activate, let me know, and I can list the groups here)

**Requested feature 2:**
The Regiment is also supported by an Air Defence battalion, broken down into 3 seperate groups. 
Would it be possible to add the following:
If a HARM is fired at the group, the radar shut down on the group. Random delay of 2-6 seconds after launch of HARM before the site shuts down. Let the radar be off in a random interval between 60-180 seconds before active again.

SAM group names:
12th_motorized_AD_batt1
12th_motorized_AD_batt2
12th_motorized_AD_batt2_2

**Comment by 132nd-Entropy** [comment]
on it. totally prefer not to use flags ( a nightmare for troubleshooting and finding stuff), will use a list of groups to activate instead

12th_Motor_Regiment_HQ
12th_Motor_regt_arty_batt
12th_motorized_AD_batt1
12th_motorized_AD_batt2
12th_motorized_AD_batt2_2
Motorized_Plt_1_1_1
Motorized_Plt_1_1_2
Motorized_Plt_1_2_1
Motorized_Plt_1_2_2
Motorized_Plt_1_3_1
Motorized_Plt_1_3_2
Motorized_Plt_2_1_1
Motorized_Plt_2_1_2
Motorized_Plt_2_2_1
Motorized_Plt_2_2_2

**Comment by 132nd-Entropy** [comment]
done, derived the above table from the trigger in the ME so should be working. feature 2 was also added and tested
