### ISSUE TITLE
REQ HELP: Range 14 AR / EX GREEN STORM

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/ATRM#56]
For EX Green Storm I have created a tasking for AR tasking for Range 14
(Link: https://132nd-vwing.github.io/ATRM_Brief/Pages/R14_AR_TASK.html )

In the .miz I have set all these groups now as late activated, and in the trigger list, I have created a trigger with condition Flag is true 101, then all groups activate.

**Requested feature 1:**
Add a F10 menu which says: EXGS - Activate AR R9
Once this is pressed, it set Flag 101 to true.

(So the groups will be activated. If you prefer to manually script them to activate, let me know, and I can list the groups here)

**Requested feature 2:**
The Regiment is also supported by an Air Defence battalion, broken down into 6 seperate groups.
Would it be possible to add the following:
If a HARM is fired at the group, the radar shut down on the group. Random delay of 2-6 seconds after launch of HARM before the site shuts down. Let the radar be off in a random interval between 60-180 seconds before active again.

SAM group names:
21st_MBT_RGT_AD_batt_1_1
21st_MBT_RGT_AD_batt_1_2
21st_MBT_RGT_AD_batt_2_1
21st_MBT_RGT_AD_batt_2_2
21st_MBT_RGT_AD_batt_2_3
21st_MBT_RGT_AD_batt_2_4

**Comment by 132nd-Entropy** [comment]
completed. deleted the triggers and flags, used the below table to activate the groups  (derived from Flag101 trigger). 
All groups spawn with AI off, and FLAG 101 will be activated, so the step-wise activation of the AI will still be done via the triggers you set in the ME. 


      "21st_MBT_RGT_1_1_1";
      "21st_MBT_RGT_1_1_2";
      "21st_MBT_RGT_2_1_1";
      "21st_MBT_RGT_1_1_2";
      "21st_MBT_RGT_2_2_1";
      "21st_MBT_RGT_2_2_2";
      "21st_MBT_RGT_AD_batt_1_1";
      "21st_MBT_RGT_AD_batt_1_2";
      "21st_MBT_RGT_AD_batt_2_1";
      "21st_MBT_RGT_AD_batt_2_2";
      "21st_MBT_RGT_AD_batt_2_3";
      "21st_MBT_RGT_AD_batt_2_4";
      "21st_MBT_RGT_AD_radar";
      "21st_MBT_RGT_arty_batt1";
      "21st_MBT_RGT_arty_batt2";
      "21st_MBT_RGT_support_special";
      "21st_Support";
      "21st_Support_ammo";
      "21st_Support_ammo2";
      "21st_Support_food1";
      "21st_Support_food2";
      "21st_Support_fuel1";
      "21st_Support_fuel2";

**Comment by 132nd-Entropy** [comment]
completed, but request testing. I see in the log that all above are spawned, but I dont see them on the F10 map, or only a few of them.

**Comment by 132ndNeck** [comment]
Same here as on Issue #52 
When units are spawned in, they get  a number associated with them  as shown on the picture below:
![bilde](https://user-images.githubusercontent.com/26002570/75592227-0d15c400-5a82-11ea-8786-063ec56878eb.png)


Original name in the ME:
![bilde](https://user-images.githubusercontent.com/26002570/75591897-439f0f00-5a81-11ea-83bd-2142297d3d1e.png)

This messes up triggers, as they use the original name, as shown below. 
![bilde](https://user-images.githubusercontent.com/26002570/75591966-65989180-5a81-11ea-892d-7ff42222a1e4.png)

**Comment by 132nd-Entropy** [comment]
same answer as for the other issue, unable to fix this, as script-spawned units always get a number 001, 002 etc added.

**Comment by 132ndNeck** [comment]
Copy. Added a workaround for tonights training, and disabled the loading of the R14 script at startup

**Comment by 132nd-Entropy** [comment]
closing for now then

**Comment by 132ndNeck** [comment]
Correction. This script is in the same file as Range 14, CAS. So I will not do anything with this script, so I dont mess up anything.

Would it be possible to delete the AR function ? (Line 157-264)  (as I want the R14 CAS part to still be in the .miz.)
But to have the R14 AR functionality will need to rely on triggers for now unless you know a workaround ?

**Comment by 132nd-Entropy** [comment]
confirm you then also lose the IADS scripting?

**Comment by 132nd-Entropy** [comment]
done

**Comment by 132ndNeck** [comment]
> 
> 
> confirm you then also lose the IADS scripting?

Yes, unless as you are able to script the entire scenario from scrath using only scripting.
The combination triggers and scripting does not work, as mentioned above.

**Comment by 132nd-Entropy** [comment]
done
