### ISSUE TITLE
REQ HELP: Range 7: CAS, High Value Target

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/ATRM#57]
I request some help for adding the following to a CAS scenario at Range 7.
Information about the scenario is found here: https://132nd-vwing.github.io/ATRM_Brief/Pages/R7_CAS_TASK.html

**Feature request 1:**
Add a F10 menu to activate the scenario.
This is to activate the groups so they are visible for FAC(A) / JTAC for mission planning/preperation before CAS flights are on station.
The following groups are set to late activation and need to be activated:
- R7_CAS_Outpost_AD
- R7_CAS_Outpost_AD_Manpad
- R7_CAS_IFV_PLT1
- R7_VIP_convoy1

**Feature request 2:**
Add a F10 menu to start the scenario.
This to start the actual scenario. Will be activated by the JTAC / FAC(A) once the CAS flight checks in at the CP.
Once this F10 option is clicked, activate FLAG 110.

**Comment by 132nd-Entropy** [comment]
wrote the script, but getting an error, those templates don't exist. 
also, I don't see a trigger using FLAG 110?

**Comment by 132nd-Entropy** [comment]
@132ndNeck

**Comment by 132ndNeck** [comment]
> 
> 
> wrote the script, but getting an error, those templates don't exist.
> also, I don't see a trigger using FLAG 110?

![bilde](https://user-images.githubusercontent.com/26002570/71622783-75f2d400-2bd8-11ea-954f-c1809fb6f481.png)

**Comment by 132ndNeck** [comment]
Also, the units are there, just verified:
(all set to late activation and are hidden).
![bilde](https://user-images.githubusercontent.com/26002570/71622803-9e7ace00-2bd8-11ea-89bf-512e6caeaed6.png)

**Comment by 132ndNeck** [comment]
As a workaround, currently they can be activated here: (By moving the vehicle toward the flag)
![bilde](https://user-images.githubusercontent.com/26002570/71622831-c66a3180-2bd8-11ea-9b3e-fd7d2bfd31d8.png)

**Comment by 132nd-Entropy** [comment]
check your screenshot and the names of the groups you posted in your first post, they dont match.

**Comment by 132nd-Entropy** [comment]
setting the script to use those 2 groups, please let me know if more should be included
R7_HVT_convoy1
R7_HVT_IFV_PLT1
