### ISSUE TITLE
Flight Configs

### ISSUE THREAD

**Issue by daviddcs** [132nd-vWing/ATRM#59]
Some flights are missing immortal settings.

F14's - Ras Al Khaimah
F16's - Sas Al Nakheel
F14's - Sas Al Nakheel
F14's - Al Dhafra AB

A10's and Heli's as well but that might be by design?

**Comment by 132nd-Entropy** [comment]
I rahter have the F14s not set to immortal, as well as teh A10s. Keeps us on our toes.

**Comment by 132ndNeck** [comment]
Fixed
