### ISSUE TITLE
On demand AEW

### ISSUE THREAD

**Issue by daviddcs** [132nd-vWing/ATRM#6]
- Not having AEW assets in play constantly should improve performance.
- Enabling the use of different "tracks" would allow the "SD" to position the platform for suitable radar and radio coverage.
- Not having constant AEW assets, allows for training w/o E3 or E2 datalink support for hornets
- Having different tracks is not so complicated, you set a trigger to switch-waypoint to a waypoint preceding the waypoint with the orbit(trigger)
- Allows for the ability to restrict E3/E2 use to when a 176th is on station.
- Allows for using alternate radar sources for EW. (ground based GCI gameplay)

**Comment by 132ndNeck** [comment]
Same as tankers, suggestion setting up various tracks
(one for default training, so event hosts do not necessarily need to do anything) but adjustable for a scenario if a controller want to change

**Comment by 132ndNeck** [comment]
Various AWACS availeble on demand.
