### ISSUE TITLE
AAR402 does not respond to 144.000Mhz

### ISSUE THREAD

**Issue by jkhoel** [132nd-vWing/ATRM#61]
During our flight tonight, version 2.2.2 of the mission - AAR402 did not respond to me nor my WM. We could hear each other on 144.000Mhz, the published freq in both the docs and the briefing

**Comment by daviddcs** [comment]
It's spawn on demand?

**Comment by jkhoel** [comment]
Correct. I didn't think about it at first. But when we tuned to 44X after departure we got no return. I did the F10 menu thing, and it instantly popped up sweet on the TACAN.

**Comment by 132nd-Entropy** [comment]
fixed
