### ISSUE TITLE
Callsigns KNIGHT and KNIFE too close

### ISSUE THREAD

**Issue by evilivan** [132nd-vWing/ATRM#62]
We experienced some confusion because callsigns KNIGHT and KNIFE are very close and hard to distinguish on comms. Can we ditch one?

**Comment by 132ndNeck** [comment]
Yes.
With the new tasking feature we dont have the standard callsigns, but will keep the flight list, so will be adjusted as the tasking system on the website gets tacan, lasercodes, IFF,etc.

(also possible for event hosts to make sure only one of the callsigns are in use.

**Comment by 132nd-Entropy** [comment]
can the issue be closed?

**Comment by 132ndNeck** [comment]
Yes
