### ISSUE TITLE
Stennis recovery tanker not on advertised freq and TACAN 

### ISSUE THREAD

**Issue by evilivan** [132nd-vWing/ATRM#63]
We tried to use the recovery tanker on the following freqs and TACANs with no response:

142.500
141.000
64Y
48X

**Comment by 132nd-Entropy** [comment]
checked the script it should work. I wonder why it didnt. 
`-- S-3B Recovery Tanker spawning in air.
local tanker=RECOVERYTANKER:New("CVN74_STENNIS", "CVN74_STENNIS_Tanker IFF#IFF5321FR")
tanker:SetRespawnInAir()
tanker:SetRadio(142.5)
tanker:SetModex(511)
tanker:SetTACAN(48, "C74")
tanker:__Start(3)`

**Comment by 132nd-Entropy** [comment]
did you check on teh F10 map if the tanker was airborn at the the time? Also, did you check the status of the Tanker via the script F10/other/Airboss..

**Comment by martinco** [comment]
I did eventually get the TCN from kneeboard and that worked on 48 (can't recall x/y) - but no joy on freq (forgot to hit record)

Didn't know about f10 airboss tanker info, will keep in mind next time if it shows freqs too

**Comment by 132nd-Entropy** [comment]
I assume the tnaker was out of fuel and it took until the new one was on station

**Comment by 132nd-Entropy** [comment]
asking people to re-check this and see if this is still a persisting issue or if it can be closed

**Comment by evilivan** [comment]
I tested the recovery tanker today and it seemed to work fine. I was with Jester, so I don't know what TACAN he tuned in the back (sorry, should have checked manual tune...), but it did work for the tanker, and tanker responded to 142.500 and I was able to take fuel.

**Comment by martinco** [comment]
Yea, I suspect we didn't try that combination - i'm 100% sure of 64Y/142.500 as per https://132nd-vwing.github.io/ATRM_Brief/Files/ATRM%20freqs%20overview.pdf (which isn't correct) and 48X/141.000
 (in so much that when i change the TCN i changed the freqs)  but never tried 48X +  142.5 so it was probably just that
