### ISSUE TITLE
ATRM 2.2.5 requires WWII Assets pack

### ISSUE THREAD

**Issue by 132nd-Inigo** [132nd-vWing/ATRM#69]
![2 2 5 WWII assets pack requirement](https://user-images.githubusercontent.com/54333457/73669924-fa8db200-46b0-11ea-81d4-1ec7b240baf4.png)
A paid addon is required to enter the server, which not everyone might have. Can this be fixed?

**Comment by 132ndNeck** [comment]
Not sure where this comes from. Was not there previous.
I saw that @steven-omaha  did some edits in the mission , and that @132nd-Entropy did publish  2.2.5.

Maybe one of you guys know?

**Comment by steven-omaha** [comment]
Did not happen on my end.

**Comment by steven-omaha** [comment]
Was appearantly introduced by accident from @132nd-Entropy in commit e015f49.

https://github.com/132nd-vWing/ATRM/commit/e015f4980cf4a8d758d765bc1134d6fbabbec18a#diff-6c654debfa4cef1de4995df5feb61889R221862
