### ISSUE TITLE
No landing lights at OMAM

### ISSUE THREAD

**Issue by steven-omaha** [132nd-vWing/ATRM#70]
Was flying on the dedi tonight, mission was running for quite a bit, ATIS was at November. In game it was night time. 

Landing lights at OMAM war inactive. Even after contacting AI TWR, they stayed off. Tried to reproduce in single player and locally hosted MP, without success.

Has this ever happened, or is this a known issue?

**Comment by 132ndNeck** [comment]
I dont think we can control the landing lights in any way. So not sure what we can do about it? OR what you want us to do with it? (Since you are raising it as an issue here)

**Comment by steven-omaha** [comment]
I wanted to ask if this has ever happened before. If there would have been a pattern, we could investigate this. Since this apparently not the case, this can be closed.

**Comment by 132ndNeck** [comment]
Copy, closing this as it is not something we can do about the lights from the ME or scripting.

**Comment by steven-omaha** [comment]
Had no landing lights today again. Was that also the case for the other pilots? If so, we need to figure out how we can trigger this so that we can file a bug report with ED.
