### ISSUE TITLE
respawning threatsites

### ISSUE THREAD

**Issue by steven-omaha** [132nd-vWing/ATRM#74]
For 617-TAC-04 we now have Threatsites 21 to 24 (Tunguska, Strela 1, Strela 10, Igla, see PR #68 and issue #45). Each TS has one launcher and one ammo truck. The launchers need so much time rearming that even training as a singleton I need to wait that these four TS finally rearm, and therefore spend time flying back and forth between them until finally something shoots at me again.

Can we have an option (only for range 2 at first) that despawns and respawns all the threatsites in the range to circumvent this problem? Ideally the threatsites should be in the same state (active / deactive)  before and after respawn, so that the pilot does not need to activate them all again.

**Comment by 132nd-Entropy** [comment]
sure!

**Comment by 132nd-Entropy** [comment]
I was quite busy, will try to get this done asap sry

**Comment by 132nd-Entropy** [comment]
done. testing requested. Also fixed Range 9 menu entries appearing in the ranges 1-6 submenu
