### ISSUE TITLE
Deconfliction Range13 vs. HEXX

### ISSUE THREAD

**Issue by 132ndhitch** [132nd-vWing/ATRM#76]
In Range 13 strafe pits and bombing circles are to close to NAV-Point HEXX (MANSA-3 departre).

**Comment by jkhoel** [comment]
I can't find the source, it seems to have been lost from the Rage 13 information page. But I believe this range has a ceiling of 3000 FT, and as such that should not be an issue (except for frag). This is first and foremost a range designed for RWs.

**Comment by 132ndhitch** [comment]
Ok, make sense! That's a FNG booby-trap.

**Comment by 132nd-Entropy** [comment]
good call @jkhoel I made a PR to add a ceiling of 3000ft AGL, waiting pending @132ndNeck's approval

**Comment by 132ndNeck** [comment]
Thanks @132nd-Entropy 
PR approved, and this Issue can be closed.
