### ISSUE TITLE
REQ HELP - Range 6 moving targets

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/ATRM#77]
Based on the CBU lesson made by  @steven-omaha I have setup Range 6 with 4 different moving targets.
3 targets follow the road (slow, medium and high speed), and one group of 8 veichles in the terrain.

All 4 groups currently set as late activation, but they have the formation , speed and waypoints in place.

Information about the groups:
All groups starting close to T6.1, in area marked as yellow below.
![bilde](https://user-images.githubusercontent.com/26002570/75584710-a1772b00-5a70-11ea-9479-311a4eeea24e.png)

R6_MovingTGT_1_Slow
7kts, 6 veichles follow road EAST
Suggested name: Road_Slow

R6_MovingTGT_2_Medium
15kts, 4 vehicles, following road EAST
Suggested name: Road_Medium

R6_MovingTGT_3_High
30kts, 2 veichles, following road EAST.
Suggested name: Road_Fast

R6_MovingTGT_4_Terrain
7kts, 8 veichles, in terrain in various formations toward EAST (SOUTH of the EAST-WEST road)
Suggested name: Terrain_Slow

**FEATURE REQUEST**
Is it possible to add a F10 menu to start one of the 4 groups individually? So the flight that are doing training can activate target as needed for their training.

**Comment by 132nd-Entropy** [comment]
to avoid confusion and redundant work, is this done via scripting or ME triggers?

**Comment by 132nd-Entropy** [comment]
bump @132ndNeck

**Comment by 132ndNeck** [comment]
Currently everything is input in the ME via triggers. But if you are able to change it into F10 menus and scripting only, it will be cleaner and  better.

**Comment by 132nd-Entropy** [comment]
definitely. see isssue #85
