### ISSUE TITLE
Tanker MOA1

### ISSUE THREAD

**Issue by 132ndhitch** [132nd-vWing/ATRM#78]
- Tanker AR304
- Tanker AR302
- Tanker AR404 (Red)
- Tanker AR201 (from Dex's AAR)

were not on Station on Sunday's mission.

**Comment by 132nd-Entropy** [comment]
some tankers are supposed to spawn only on demand. thats why there is a F10/other/Tankers menu. Can you confirm that those are supposed to be airborn without being triggered by F10 menu?

**Comment by 132ndNeck** [comment]
Those tankers are all supposed to be spawned by F10 map when needed.
AR201 is currently active, but should be set to a similar state, ref latest comment in Issue #15 
AR201 have normally always worked, so not sure why it did not ref Dex's AAR. Think  that need more troubleshopting.

But closing this issue, as the tankers mentioned need to be activated by F10, and thus it is intentionally that they are not on station by defaul

**Comment by 132ndhitch** [comment]
Gumidek used F10 menu to call Tanker: Tanker has no race track see picture
https://media.discordapp.net/attachments/555836346531315733/684330032357048334/Unbenannt.JPG
