### ISSUE TITLE
Tanker TACAN does not point at the tanker

### ISSUE THREAD

**Issue by 132Ashilta** [132nd-vWing/ATRM#80]
When spawning Tankers in the ATRM, I have noticed that both the Viper and the Hornet do not relate accurate to the tanker, certainly in the early minutes of spawning the tanker. The following image depicts: https://imgur.com/a/mBzBcjm

I am south of the tanker, the tanker is heading West and I am turning left to right to reach the tanker. The TCN is boxed on the HSI and the indicator _believes_ I should be flying 094 to reach the tanker - clearly incorrect. In the Viper, if I spawn the bearing knob to get a direct bearing to the Tanker, the position of the TACAN appears not to update. Either I'm doing something _really_ stupid or this doesn't work!

**Comment by 132ndNeck** [comment]
Weird. 
We had some TACAN issues earlier , but that was caused by tankers using the same TACAN freq. This was resolved some time ago, and I have not seen any issue with the TACAN (AR 201 and AR203. not tested any other tankers)

I will test on tonights event and see if I get the same issue to troubleshoot

**Comment by 132ndNeck** [comment]
Confirmed. I saw an issue with AR203. But did not experience any issue with AR201.

After looking in the .miz I might have found what is causing it:

In AR201, the TACAN is tied to the unit (see screenshot below).
However for AR203, it is not tied to the unit (see screenshot below).
This is the only difference between the two as far as I can see. I will update in the .miz now.
Please report if this still is a bug after next test on the .miz (after sunday)


![bilde](https://user-images.githubusercontent.com/26002570/76024409-5a36e180-5f2b-11ea-9611-4e085e1ef852.png)

![bilde](https://user-images.githubusercontent.com/26002570/76024532-966a4200-5f2b-11ea-90b4-6aa7c30a2980.png)

**Comment by 132Ashilta** [comment]
Thanks Neck - ping me if you manage a release early. It doesn't take long to test

**Comment by 132nd-Entropy** [comment]
I updated the tacans for the various tankers, 2 were set wrong in the ME, and the carrier rescue tankers conflicted with others. I think this might be solved now. please test
