### ISSUE TITLE
Tanker MOA1 #Issue 78

### ISSUE THREAD

**Issue by 132ndhitch** [132nd-vWing/ATRM#81]
Gumidek used F10 menu to call Tanker: Tanker has no race track see picture
https://media.discordapp.net/attachments/555836346531315733/684330032357048334/Unbenannt.JPG

**Comment by 132ndNeck** [comment]
Hmm. That is weird. I just checked in the .miz now, and the tanker appear to have the racetrack orbit set (see screenshot below).
Will need to troubleshoot and have someone test again next time the tanker is used.

![bilde](https://user-images.githubusercontent.com/26002570/75977795-6f851f00-5edd-11ea-8b03-e42c032a8365.png)

**Comment by 132ndNeck** [comment]
Confirmed. It did the same thing when I tested now.

**Comment by 132nd-Entropy** [comment]
confirmed as well, made refuelling quite challenging. they are set correctly, seems like a DCS bug

**Comment by 132ndNeck** [comment]
Strange.  Maybe we should try to simply change the racetrack a little, and see if it still have the same issue. Weird that no other tankers have this issue, as the rest of the tankers do their racetrack as they are supposed to do.
