### ISSUE TITLE
triggers in the ME, Menus, triggers to activate ranges, 

### ISSUE THREAD

**Issue by 132nd-Entropy** [132nd-vWing/ATRM#85]
right now, we have menus in place that activate all functions such as range menus, etc etc
on top, there are vehicles that start certain functions. I think this is messy. can I request the following:

all triggers that are started by moving a vehicle into a zone could instead be activated by a flag.
I then write the menu, properly nested to the corresponding root menus, and by activating it, that flag will be called. that way, Mission editors can still use the ME triggers, and all those triggers can remain unchanged, with the exception of the very initial trigger, that is now called when a certain flag is true. 
would  you agree?

**Comment by 132ndNeck** [comment]
Yes, that is doable, and suggest further that the veichle will still be present as a backup solution.

I will go in and change the various activations and set them as flags instead, (currently they start the scenarios, not activate a specific flag).

**Comment by 132ndNeck** [comment]
All scenarios that is possible to start by a vehicle is now given a flag, so that it can be added to the F10 menu.
(I kindly request that we keep the vehicles there as a backup, so please do not delete them)

See Issue #90

**Comment by 132nd-Entropy** [comment]
I did not read about not deleting the vehicles, sorry, but they should not be needed. if ever issues arise with the menus, which I dont think there will be, I will add them back
