### ISSUE TITLE
using flags in the mission editor

### ISSUE THREAD

**Issue by 132nd-Entropy** [132nd-vWing/ATRM#86]
can I request we have a text file where all flags that are in use be documented, else it gets messy really fast. it could be in the form of an 'issue' here on gh for example

**Comment by 132ndNeck** [comment]
Yes, I can compile a list, when I change the activations later, and set the various starts to flags instead of activating them directly

**Comment by 132ndNeck** [comment]
See Issue #90 

Closing this, as the FLAGs are in  Issue 90
