### ISSUE TITLE
new convoys on range 4 do not move

### ISSUE THREAD

**Issue by steven-omaha** [132nd-vWing/ATRM#87]
Activated the range, first convoy started moving. After it was considered destroyed, the second group spawned. It wouldn't move. I could not move them manually via F10 map. I pinged Assaf who logged in as tactical commander, and couldn't move them either.

**Comment by 132ndNeck** [comment]
This is weird.

![bilde](https://user-images.githubusercontent.com/26002570/77108847-3abbb080-6a23-11ea-9188-6e98c2659363.png)


Just tested and the convoys seem to be moving, and working as intended. Did you engage the second convoy immediatly after it was spawned?  Maybe if they are attack while regrouping it causes the group to be stuck.

If the second convoyed spawned there is nothing that indicate that it should not move.

I suggest we do another test for this.

**Comment by steven-omaha** [comment]
> Did you engage the second convoy immediatly after it was spawned?
Negative. I waited a few minutes. Even Assaf couldn't move them, only by entering one vehicle.

**Comment by steven-omaha** [comment]
I tried this again a while back, was working that time. Issue can be closed.

**Comment by 132ndNeck** [comment]
Great!
