### ISSUE TITLE
REQ HELP: Activate by F10: ATIS/Carrier groups

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/ATRM#88]
Hello!
Would it be possible to adjust and spawn the following by F10 (on demand), since these functions are not used on all training missions, and then it can be off by default to reduce strain on the server, but having the option to activate it via F10:

**ATIS:**
- Liwa
- Al Minhad
- Sas Al Nakheel
- Ras Al Kaihma
- Fujairah
- Khasab

(So basicly only ATIS that is active by default is Al Dahfra and Al Ain, as those are mostly used)

**Carrier groups:**
- Rescue helicopter and tanker for both carriers (blue and red)
- Red Carrier

(So basicly on the blue carrier is on by default, but the tanker and rescue helicopter for blue carrier must be activated by F10 before use if required)

**Comment by 132nd-Entropy** [comment]
done. ATIS is now activated using F10 /misc

rescue helo and carrier tankers will start up only when the carrier starts recovery. all recovery windows are removed, and need now be started manually via airboss/kneeboard/skipper menu
