### ISSUE TITLE
ATIS not readable for Controllers using EAM

### ISSUE THREAD

**Issue by Looney1976** [132nd-vWing/ATRM#89]
When controllers use SRS EAM and not DCS, we are unable to copy the ATIS broadcast.
I've discussed this with Ciribob and he asked me to check the coalition security and turn it off.

Can you guys do that?

**Comment by 132ndNeck** [comment]
This is already off (see screenshot below):

![bilde](https://user-images.githubusercontent.com/26002570/77111013-d6025500-6a26-11ea-99a5-d526c0011b85.png)


So coalition security is likely not causing it.

**Comment by Looney1976** [comment]
OK, Ciribob asked if we can set LOS off and see if that solves it.
Should be easy to do that off-hours. I'll make arrangements.

**Comment by 132nd-Entropy** [comment]
I turned off LOS if that helps
