### ISSUE TITLE
Thoughts on range construct.

### ISSUE THREAD

**Issue by daviddcs** [132nd-vWing/ATRM#9]
Presuming here that Advanced training focuses on LFE's.

I think very little effort should be put into declaration of different ranges. Work it more like a mission, have a large range and modify/de-conflict with use of ACP/ROZ/ROE/HARDDECKS. Work assets closer together instead of having a +300NM spread.
Less work on different range orders, more work on targets and types of tasking.

**Comment by 132ndNeck** [comment]
This new training mission will be made to facilitate both LFE and normal trainings.

So the training mission will need to contain both to facilitate day-today TRP for various squadrons while at the same time be a place to conduct advanced trainings and LFEs

**Comment by 132ndNeck** [comment]
What I suggest is on a github briefing page, we create various options.

1. "Normal training" for the entire map. (TRP focus)
2. One part normal training, and one part advanced training (Advanced training, LFE focus with bigger airspace and integration)
3. LFE focus
