### ISSUE TITLE
RANGE 2 / SEAD Training 

### ISSUE THREAD

**Issue by 132ndhitch** [132nd-vWing/ATRM#93]
Last week I was shooting HARMs against SA-3/6/8 and all hits. I think the IADS script (turn off Radar after Harm launch) is not implemented there.

for advanced SEAD/DEAD-Training I have two requests:

- can you please implement the IADS script for (at least) SA-3/6/8 on Range 2? 
- is it possible to place a tanker near RG2? Otherwise we need to use AR201/AR301 in Range9 or AR304 in RG1/MOA1.

**Comment by 132ndNeck** [comment]
That is correct, Range 2 do not contain any IADS script, as Range 2 is for practicing basic SAM evasive manuevers.

SAM IADS are placed in range 12, and Range 10/11 (Still WIP)

**Comment by 132ndhitch** [comment]
I'm sorry. I will investigate RG10,11 and 12.

**Comment by 132ndNeck** [comment]
@132ndhitch I was a bit too fast when answering. Correction, we actually implemented (or planned to implement) basic IADS implementation for Range 2 aswell. See #27 
Not sure why it is not working.

@132nd-Entropy When you have time, would you be able to look into if there are some errors making the SAMs not shut off when they are beeing fired at?

**Comment by 132nd-Entropy** [comment]
I just tested this with TS7, it worked as intended. @132ndhitch could you provide more detail please, what TS did you fire at exactly?

**Comment by 132nd-Entropy** [comment]
also tested on range 2, TS13, which is an SA3. works as intended. you get all the log entries, sam shutting down the radar, etc. some radars cant move,  maybe that confused you, ?

**Comment by 132ndhitch** [comment]
We shot Harms against SA3/6/8 and all Harms hits. Because all Harms hit the radar-sites, I thought IADS is not active at this threats.
I will test it again today.

**Comment by 132ndNeck** [comment]
@132ndhitch 
Confirm you actually activated the threat sites in Range 2?  You need to manually activate them. Go into the F10 menu -Ranges - Range 2.

**Comment by 132ndhitch** [comment]
Confirm. F10 - Txy activate. All Sam's have  launched missile on us.
Stay, will check it in few minutes.

**Comment by 132ndhitch** [comment]
I activate SA3/6/8/15 1min before we engaged the SAM via F10 menu. No message popped up, but according to F10-> RG2 -> see active SAM all SAMs were active.
According to my TACVIEW and what I saw from 15k ft all HARMs hit the SAMs. (what happen to the HARM when SAMs will deactivate their radars? I think HARMs will go stupid.)  https://www.dropbox.com/s/opdavzgbkp8bp4l/Tacview-20200408-203059-DCS-ATRM_2.zip.acmi?dl=0
Because all HARMs hit the radar - I cannot say that the radar was turned off. 

Point2 from 1. thread: From carrier we need to enter MOA1/Range1 to hit the Tanker. After we finished training in Range2 we should go to the tanker for ~3000LBS of fuel, but in MOA1/RANGE1 was a exercise with active missile and we don't want to interrupt the training. Is it possible to place a tanker near RG2? Possibly AR304 50nm to the south?

**Comment by 132ndhitch** [comment]
maybe we shot from too short a distance (<10nm) ?!

**Comment by 132nd-Entropy** [comment]
ok, I can't reproduce this not working. If your harms still hit, maybe , as you say, you were too close and the SAM unit did not shut down the radar in time. There is a time delay built in, I can change this easily. 

the easiest way to test is this: 

fly towards the sam, left click it on the F10 map, then go F7 to watch the  SAM in outside view. You want to see the radar dish rotating, meaning its active, als can be verified on your RWR. 

now fire your HARM, and observe after launch again in F7 outside view. The SAM should, after some delay, stop its radar (dish stops rotating), and the RWR painting should stop. 

If so, the script works. If you're too close, we can easily decrease the delay between the HARM launch and the RADAR shut off.

**Comment by 132ndhitch** [comment]
Thank you for testing and the good description. I will try this next week.
