### ISSUE TITLE
Add a "replay" and a "ping " for messages directed for JTACs in ranges

### ISSUE THREAD

**Issue by IAFAssafB** [132nd-vWing/ATRM#95]
When JTACing, the "GFC" or "MORTAR TEAM" messages are neat! I'd appreciate two additions if not too difficult:
1) Add a sound whenever a message is displayed (a ping of some sort). I often Alt-Tab from the DCS to other (usually Excel for the CAS briefs) and not always having eyes on those messages

2) If possible to add a menu item , something like "replay last message"...
Thanks!

**Comment by 132nd-etcher** [comment]
I second the request for a possibility to replay the last message or have access to the message history.

**Comment by 132nd-Entropy** [comment]
unable, as this scenario is done by clasical ME triggers and not by scriping, so someone else needs to take this on. I assume sound to group triggers could simply be added?

**Comment by IAFAssafB** [comment]
Rgr thanks ! Will look into it.

**Comment by 132nd-Entropy** [comment]
*bump*

**Comment by IAFAssafB** [comment]
Wow thanks for the reminder! Totally missed it :-/

**Comment by 132nd-Entropy** [comment]
same issue as the request with the mortars and a beeping sound.

**Comment by 132nd-Entropy** [comment]
https://github.com/132nd-vWing/ATRM/issues/111

**Comment by 132nd-Entropy** [comment]
hi can this be closed?
