### ISSUE TITLE
Range 15 AR Company-Battalion size on demand scenario

### ISSUE THREAD

**Issue by 132ndJunior** [132nd-vWing/ATRM#97]
Kindly requesting for creation of on demand AR Scenario which would allow to spawn in up to mechanised battalion on Range 15. Preferably spawn in may happen company by company (12-15 vehicles at a time), controlled by scenario manager to avoid server overstrain and control training conditions.

Scenario layout in link below:
https://drive.google.com/open?id=1m8XjbLfg1YrNde2I0lJofbt1BRZFTgZ5

SUGGESTED SCENARIO TEXT FOR ATRM BRIEFING PAGE:

SITUATION

Enemy - Mechanised Infantry Battalion has been spotted marching through the mountains on Liwa - Al Ain Route 7. While stationed in Liwa 24hrs ago ISR assets confirmed 20+ BMP 2/3 and up to company of MBTs attached. By the doctrinal pattern Battalion may be covered by organic combination of ZSU-23-4 Shilka and SA-13 Gopher. SA-19 Tunguska may be attached along with MBTs.

Friendly - Motorised infantry battalion is withdrawing from Mahdah to reinforce Al Ain defences and join with national guard unit already in deployed to the city.
Friendly force is not capable of facing mechanised battalion in the field.

Most likely course of action(MLCOA) - mechanised battalion will seize Mahdah (N 24 23.900 E 055 58.300) to facilitate conditions for two pronged attack - along Route 7 and from Mahdah direction.

Most dangerous course of action (MDCOA) - mechanised battalion will assault Al Ain directly along Route 7 posing threat of meeting engagement with marching friendly motorised infantry battalion.

MISSION

Conduct Armed Reconnaissance between N 24 15.077 E 056 05.845 and N 24 22.984 E 055 59.816 in order to:
a) detect and define mechanised battalion course of action,
b) destroy at least 20% of MBTs and at least 20% of BMPs,
c) deny freedom of maneuver.

TARGET PRIORITY

1. ADA (Air Defence Assets)
2. MBT
3. BMP

ABORT CRITERIA

Mechanised battalion reached Mahdah town.

**Comment by 132nd-Entropy** [comment]
happy to take this on but need more info and help. 

1. place the units you want to spawn in into the ME as late activated, and label the group names so that they make sense. Then state the group names here, as I'd need them for the script. 

2. spawn in can happen over time, as you request. so I suggest in 1, you make one group per 'time interval' and let me know how the subseuent groups should be spawned in. (time delay, or F10 menu entry). Anythign is possible, but I'd need to know exactly the design before I start writing the script. 

3. that assumes this is cleared by @132ndNeck

**Comment by 132ndJunior** [comment]
Thank You @132nd-Entropy , I'll do that. If not today, then tomorrow

**Comment by 132ndJunior** [comment]
Ok, done, link to .miz file: https://drive.google.com/open?id=10qvBoATsLNvtqtztuNLa6rVHVyIxgxUo

Group names in sequence:

R15_AR_Recce_1
R15_AR_Recce_2
R15_AR_MBT_PLT1
R15_AR_IFV_PLT2
R15_AR_IFV_PLT3
R15_AR_IFV_PLT4

I think that it would be fine if they spawn in at the same time. What I'd find usefull is possiblity to spawn them two or even three times, having one company per wave. Not sure if having entire battalion would impact server's performance though, I rely on Your judgement.

**Comment by 132ndNeck** [comment]
Yes, thumbs up from me.

**Comment by 132nd-Entropy** [comment]
I must have totally overlooked this, aplogies @132ndJunior for the long wait. I put it in as requested, right now, the scenario is started by a F10 menu command "Range 15 AR Attack on Mahdah" in the Range 15 submenu. This will spawn in all vehicles at hte same time. Don't worry about server strain, if vehicles are spawned in via MOOSE this will cause not much lag, as moose uses a clever logic where the late-activated units are already pre-registered at mission load so there should not be any lag (unlike units spawned in via custom ME triggers). 

if you want any changes to this very simply spawning, please let me know

**Comment by 132ndJunior** [comment]
Thank You very much @132nd-Entropy I'll give it a test on first as soon as I can!

**Comment by 132ndJunior** [comment]
We've tested the mission with Inigo tonight, awesome work @132nd-Entropy 
The way it is right now is perfect for 2-4 Ka-50 to practice, if it is possible to make that scenario activated twice or even three times (like waves) we could have really cool SCAR setup. 
Thank You very much for Your time spent on setting it up!

**Comment by 132nd-Entropy** [comment]
sure, no problem. I simply leave the F10 trigger in there even when used, so the waves can be spawned indefinitely (or x times, if you prefer)

**Comment by 132nd-Entropy** [comment]
ok! done, you can spawn reinforcements 3x, then the menu option will disappear and no more reinforcments will be available
