### ISSUE TITLE
TS 22 - 24 did not enage me

### ISSUE THREAD

**Issue by steven-omaha** [132nd-vWing/ATRM#99]
In today's mission, I activated TS 21 - 24 (range 2). TS 21 worked as it should and engaged me. None of the TS 22 to 24 engaged me. 

I checked that they were set to active in the range menu, disabled them, enabled them again, forced a rearm, nothing worked.

**Comment by 132nd-Entropy** [comment]
could you please check if they react to activating/deactivating by checking if their radar dish starts rotating/stops rotating. If so, its a case for ED

**Comment by 132nd-Entropy** [comment]
was this tested or shall we close the issue?

**Comment by 132nd-etcher** [comment]
@steven-omaha

**Comment by steven-omaha** [comment]
Sorry, forgot about this. Please leave this open until the weekend.

**Comment by steven-omaha** [comment]
Tested it in a local multiplayer with the mission from Wednesday. Works. 

Could I request that the 4 threatsites 21 - 24 default to state red? Then this can be closed. Thanks!

**Comment by 132nd-Entropy** [comment]
done
